//! The OS timer files an automation GENERATES.
//!
//! D1: `~/.yggterm/automations.json` is the source of truth and these files are
//! derived artifacts. Nothing in yggterm ever reads a schedule back OUT of a
//! unit — [`reconcile`] compares what is on disk against what the record says
//! and reports, and the record always wins.
//!
//! # Why the fingerprint exists
//!
//! A generated file that someone hand-edits is the classic way a derived
//! artifact quietly becomes a second source of truth. Silently overwriting the
//! edit loses their work; silently keeping it means the record and the timer
//! disagree and the user is debugging a job that fires at the wrong hour. So
//! every generated unit carries a fingerprint of the record it came from, and
//! [`reconcile`] can tell the three cases apart: unchanged, stale (the record
//! moved on), and hand-edited (the FILE moved on). Only the last one needs the
//! user, and it gets said out loud rather than resolved by guessing.

use std::path::{Path, PathBuf};

use crate::automation::Automation;

/// Marks a file as ours. Present on every generated unit; its absence in a file
/// occupying one of our paths means something else owns that name.
pub const GENERATED_HEADER: &str = "# GENERATED BY yggterm — do not edit.";

/// The line carrying the record fingerprint.
const FINGERPRINT_PREFIX: &str = "# yggterm-automation-fingerprint: ";

/// A file the renderer wants on disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedUnit {
    pub path: PathBuf,
    pub contents: String,
}

/// What `automation sync` found for one expected file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UnitState {
    /// On disk and matching the record.
    UpToDate,
    /// Not on disk at all.
    Missing,
    /// Ours, but generated from an older version of the record.
    Stale,
    /// Occupying our path without our header, or with our header and a body
    /// that no longer matches its own fingerprint. **Never overwritten without
    /// the user saying so.**
    HandEdited,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnitReport {
    pub path: PathBuf,
    pub state: UnitState,
}

/// Stable FNV-1a over the schedule-relevant fields of a record.
///
/// Deliberately NOT over the whole record: `runs`, `last_run_at_ms` and the
/// notice history change constantly and have no bearing on what the unit says.
/// Fingerprinting them would report every automation as stale after every run
/// and turn `sync` into noise.
pub fn record_fingerprint(automation: &Automation) -> String {
    let material = format!(
        "{}\u{1f}{}\u{1f}{}\u{1f}{}\u{1f}{}\u{1f}{}",
        automation.id,
        automation.enabled,
        automation.calendar.to_on_calendar(),
        automation.every_n_weeks,
        automation.anchor_week,
        automation.grace_secs,
    );
    let mut hash = 0xcbf2_9ce4_8422_2325u64;
    for byte in material.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01B3);
    }
    format!("{hash:016x}")
}

fn fingerprint_in(contents: &str) -> Option<&str> {
    contents
        .lines()
        .find_map(|line| line.trim().strip_prefix(FINGERPRINT_PREFIX))
        .map(str::trim)
}

/// Whether this text is a file we generated.
pub fn is_generated(contents: &str) -> bool {
    contents.lines().any(|line| line.trim() == GENERATED_HEADER)
}

pub fn service_unit_name(id: &str) -> String {
    format!("yggterm-automation-{id}.service")
}

pub fn timer_unit_name(id: &str) -> String {
    format!("yggterm-automation-{id}.timer")
}

/// `~/.config/systemd/user`, the user-unit directory.
///
/// USER units, never system ones: an automation opens an agent CLI session that
/// belongs to this human, reads their credentials and writes into their
/// checkouts. A system unit would run it as root and hand a scheduled agent a
/// blast radius nobody asked for.
pub fn systemd_user_unit_dir(home_dir: &Path) -> PathBuf {
    home_dir.join(".config").join("systemd").join("user")
}

/// Render the `.service` and `.timer` for one automation.
///
/// `exe` is the absolute path to `yggterm-headless`. Absolute because a user
/// unit inherits almost no PATH, and a unit that cannot find its own binary
/// fails at 3 a.m. with nobody watching.
pub fn systemd_units(automation: &Automation, exe: &Path, unit_dir: &Path) -> Vec<GeneratedUnit> {
    let fingerprint = record_fingerprint(automation);
    let id = &automation.id;
    let description = automation
        .title
        .clone()
        .unwrap_or_else(|| format!("yggterm automation {id}"));

    let service = format!(
        "{GENERATED_HEADER}\n\
         {FINGERPRINT_PREFIX}{fingerprint}\n\
         # Source of truth: ~/.yggterm/automations.json (automation {id}).\n\
         # Edit with `yggterm-headless automation edit {id}`, then `automation sync`.\n\
         \n\
         [Unit]\n\
         Description={description}\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         ExecStart={exe} automation run {id}\n",
        exe = exe.display(),
    );

    // Persistent=true is D3's LATE FIRE, not D3's decision. systemd runs a
    // missed timer at the next opportunity; our grace guard then decides
    // whether that late run is honoured. Splitting it this way keeps one
    // implementation of the window across all three platforms instead of
    // three OS schedulers each with their own idea of "missed".
    let timer = format!(
        "{GENERATED_HEADER}\n\
         {FINGERPRINT_PREFIX}{fingerprint}\n\
         # Source of truth: ~/.yggterm/automations.json (automation {id}).\n\
         \n\
         [Unit]\n\
         Description={description} (timer)\n\
         \n\
         [Timer]\n\
         OnCalendar={calendar}\n\
         Persistent=true\n\
         AccuracySec=1min\n\
         Unit={service_name}\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n",
        calendar = automation.calendar.to_on_calendar(),
        service_name = service_unit_name(id),
    );

    vec![
        GeneratedUnit {
            path: unit_dir.join(service_unit_name(id)),
            contents: service,
        },
        GeneratedUnit {
            path: unit_dir.join(timer_unit_name(id)),
            contents: timer,
        },
    ]
}

/// Compare one expected unit against what is on disk. Pure: the caller supplies
/// the file's current contents (`None` = absent).
pub fn unit_state(expected: &GeneratedUnit, on_disk: Option<&str>) -> UnitState {
    let Some(actual) = on_disk else {
        return UnitState::Missing;
    };
    if !is_generated(actual) {
        return UnitState::HandEdited;
    }
    let Some(stamped) = fingerprint_in(actual) else {
        return UnitState::HandEdited;
    };
    let Some(expected_fingerprint) = fingerprint_in(&expected.contents) else {
        return UnitState::Stale;
    };
    if stamped != expected_fingerprint {
        return UnitState::Stale;
    }
    // Same fingerprint but a different body means the BODY was edited: the
    // fingerprint covers the record, so it cannot notice. Comparing the whole
    // text is what catches it.
    if actual.trim() == expected.contents.trim() {
        UnitState::UpToDate
    } else {
        UnitState::HandEdited
    }
}

/// The whole reconciliation for one automation, given a reader for the disk.
/// Returns one report per expected file.
pub fn reconcile(
    automation: &Automation,
    exe: &Path,
    unit_dir: &Path,
    read: &dyn Fn(&Path) -> Option<String>,
) -> Vec<UnitReport> {
    systemd_units(automation, exe, unit_dir)
        .into_iter()
        .map(|expected| {
            let state = unit_state(&expected, read(&expected.path).as_deref());
            UnitReport {
                path: expected.path,
                state,
            }
        })
        .collect()
}

/// Unit files in `unit_dir` that we generated but no record claims any more.
///
/// A disabled or deleted automation must not leave a live timer behind. This is
/// the leak the whole feature exists to avoid, applied to our own artifacts:
/// an orphaned timer would keep opening agent sessions for a job the user
/// believes they deleted.
pub fn orphaned_units(live_ids: &[String], present: &[(PathBuf, String)]) -> Vec<PathBuf> {
    let claimed: Vec<String> = live_ids
        .iter()
        .flat_map(|id| [service_unit_name(id), timer_unit_name(id)])
        .collect();
    present
        .iter()
        .filter(|(path, contents)| {
            if !is_generated(contents) {
                return false;
            }
            let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
                return false;
            };
            !claimed.iter().any(|expected| expected == name)
        })
        .map(|(path, _)| path.clone())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::automation::parse_calendar;
    use yggterm_core::SessionKind;

    fn job() -> Automation {
        Automation {
            id: "infra-upgrade".to_string(),
            enabled: true,
            agent_kind: SessionKind::ClaudeCode,
            machine_key: "jojo".to_string(),
            cwd: Some("/home/user/gh/yggterm".to_string()),
            prompt: "some time has passed, can you upgrade again".to_string(),
            calendar: parse_calendar("Sun *-*-* 00:00:00").unwrap(),
            every_n_weeks: 2,
            anchor_week: 2_949,
            grace_secs: 21_600,
            idle_ttl_secs: 1_800,
            deadline_secs: 21_600,
            attach: false,
            title: None,
            created_at_ms: 0,
            last_run_at_ms: None,
            runs: Vec::new(),
        }
    }

    fn units(automation: &Automation) -> Vec<GeneratedUnit> {
        systemd_units(
            automation,
            Path::new("/home/user/.local/bin/yggterm-headless"),
            Path::new("/home/user/.config/systemd/user"),
        )
    }

    #[test]
    fn the_timer_carries_the_users_own_calendar_and_fires_late_when_missed() {
        let generated = units(&job());
        let timer = &generated[1].contents;
        assert!(timer.contains("OnCalendar=Sun *-*-* 00:00:00"));
        assert!(
            timer.contains("Persistent=true"),
            "a machine asleep at midnight must still get the chance to run — the GRACE guard, \
             not the timer, decides whether the late fire is honoured"
        );
        assert!(timer.contains("WantedBy=timers.target"));
    }

    #[test]
    fn the_service_names_the_binary_absolutely() {
        let generated = units(&job());
        assert!(
            generated[0]
                .contents
                .contains("ExecStart=/home/user/.local/bin/yggterm-headless automation run infra-upgrade"),
            "a user unit inherits almost no PATH; a relative exe fails at 3am with nobody watching"
        );
    }

    #[test]
    fn both_files_land_in_the_user_unit_directory_never_the_system_one() {
        for unit in units(&job()) {
            let rendered = unit.path.display().to_string();
            assert!(
                rendered.starts_with("/home/user/.config/systemd/user/"),
                "{rendered} is not a user unit — a system unit would run the user's agent as root"
            );
        }
    }

    #[test]
    fn every_generated_file_says_it_is_generated_and_where_the_truth_lives() {
        for unit in units(&job()) {
            assert!(is_generated(&unit.contents));
            assert!(unit.contents.contains("~/.yggterm/automations.json"));
        }
    }

    #[test]
    fn an_untouched_unit_reads_as_up_to_date() {
        let generated = units(&job());
        for unit in &generated {
            assert_eq!(
                unit_state(unit, Some(&unit.contents)),
                UnitState::UpToDate
            );
        }
    }

    #[test]
    fn an_absent_unit_reads_as_missing() {
        let generated = units(&job());
        assert_eq!(unit_state(&generated[0], None), UnitState::Missing);
    }

    #[test]
    fn moving_the_schedule_makes_the_unit_stale_not_hand_edited() {
        let old = units(&job());
        let mut moved = job();
        moved.calendar = parse_calendar("Sat *-*-* 02:00:00").unwrap();
        let new = units(&moved);
        assert_eq!(unit_state(&new[1], Some(&old[1].contents)), UnitState::Stale);
    }

    #[test]
    fn a_file_without_our_header_is_never_overwritten_silently() {
        let generated = units(&job());
        assert_eq!(
            unit_state(&generated[1], Some("[Timer]\nOnCalendar=daily\n")),
            UnitState::HandEdited,
            "something else owns that filename and sync must say so, not clobber it"
        );
    }

    #[test]
    fn editing_the_body_is_caught_even_though_the_fingerprint_still_matches() {
        // The fingerprint covers the RECORD, so it cannot notice a body edit.
        // Comparing the whole text is what catches it.
        let generated = units(&job());
        let tampered = generated[1]
            .contents
            .replace("OnCalendar=Sun *-*-* 00:00:00", "OnCalendar=*-*-* 09:00:00");
        assert_eq!(
            unit_state(&generated[1], Some(&tampered)),
            UnitState::HandEdited
        );
    }

    #[test]
    fn a_run_does_not_make_every_unit_stale() {
        // runs / last_run_at_ms change constantly and say nothing about the
        // timer. If they were fingerprinted, `sync` would report every
        // automation as stale after every fire and become noise.
        let before = record_fingerprint(&job());
        let mut after_a_run = job();
        after_a_run.last_run_at_ms = Some(99);
        after_a_run.runs.push(crate::automation::AutomationRun {
            run_id: "run-1".to_string(),
            due_at_ms: 1,
            started_at_ms: 1,
            outcome: crate::automation::RunOutcome::Ran,
            session_path: Some("live/jojo/0".to_string()),
            closed_at_ms: None,
            close_reason: crate::automation::CloseReason::Never,
            error: None,
        });
        assert_eq!(record_fingerprint(&after_a_run), before);
    }

    #[test]
    fn disabling_an_automation_changes_its_fingerprint() {
        let mut disabled = job();
        disabled.enabled = false;
        assert_ne!(record_fingerprint(&disabled), record_fingerprint(&job()));
    }

    #[test]
    fn a_deleted_automations_timer_is_reported_as_an_orphan() {
        let generated = units(&job());
        let present: Vec<(PathBuf, String)> = generated
            .iter()
            .map(|unit| (unit.path.clone(), unit.contents.clone()))
            .collect();
        // Nothing claims it any more.
        let orphans = orphaned_units(&[], &present);
        assert_eq!(orphans.len(), 2, "an orphaned timer keeps opening sessions for a deleted job");
        // And with the record present, nothing is orphaned.
        assert!(orphaned_units(&["infra-upgrade".to_string()], &present).is_empty());
    }

    #[test]
    fn a_foreign_unit_in_our_directory_is_never_called_an_orphan() {
        let present = vec![(
            PathBuf::from("/home/user/.config/systemd/user/someone-elses.timer"),
            "[Timer]\nOnCalendar=daily\n".to_string(),
        )];
        assert!(
            orphaned_units(&[], &present).is_empty(),
            "sync may only ever propose removing files it wrote"
        );
    }

    #[test]
    fn reconcile_reads_the_disk_through_the_caller_so_it_stays_testable() {
        let automation = job();
        let generated = units(&automation);
        let service_path = generated[0].path.clone();
        let contents = generated[0].contents.clone();
        let reports = reconcile(
            &automation,
            Path::new("/home/user/.local/bin/yggterm-headless"),
            Path::new("/home/user/.config/systemd/user"),
            &move |path: &Path| (path == service_path).then(|| contents.clone()),
        );
        assert_eq!(reports[0].state, UnitState::UpToDate);
        assert_eq!(reports[1].state, UnitState::Missing);
    }
}
